Cargo.toml, examples/minimal/server.toml, examples/tls/server.toml, examples/unified/config.toml, src/client.rs, src/config.rs, src/lib.rs, src/main.rs, src/server.rs, src/transport/tls.rs, tests/common/mod.rs, tests/config_test/invalid_config/missing_tls_client.toml, tests/config_test/invalid_config/missing_tls_server.toml, tests/config_test/invalid_config/missing_tls_server2.toml, tests/config_test/valid_config/full.toml, tests/integration_test.rs, tests/tcp_transport.toml, tests/tls_transport.toml
This PR focuses on improving the quality of the codebase, including:
- More unit tests for the config parsing
- Integration tests
- Refactor, cleanup, and chores
=> Refactor and add tests

.github/workflows/rust.yml
Resolves https://github.com/rapiz1/rathole/issues/11
=> ci: create rust.yml

Cargo.lock, Cargo.toml, src/protocol.rs
Resolves https://github.com/rapiz1/rathole/issues/8
=> Replace `ring` with `sha2`

.github/workflows/rust.yml, Cargo.toml, src/client.rs, src/helper.rs, src/lib.rs, src/server.rs, src/transport/mod.rs
Resolves https://github.com/rapiz1/rathole/issues/9
=> Add crate features

.github/workflows/rust.yml, src/main.rs
=> Treat clippy lints as errors

Cargo.lock, Cargo.toml, README.md, docs/security.md, examples/noise_nk/client.toml, examples/noise_nk/server.toml, src/cli.rs, src/client.rs, src/config.rs, src/lib.rs, src/server.rs, src/transport/mod.rs, src/transport/noise.rs, src/transport/tcp.rs, src/transport/tls.rs, tests/common/mod.rs, tests/config_test/valid_config/full.toml, tests/for_tcp/noise_transport.toml, tests/for_udp/noise_transport.toml, tests/integration_test.rs
Resolves https://github.com/rapiz1/rathole/issues/6
=> Add noise protocol as a transport

examples/systemd/rathole@.service, examples/systemd/ratholec.service, examples/systemd/ratholec@.service, examples/systemd/ratholes.service, examples/systemd/ratholes@.service
=> feat: add systemd unit files

.github/workflows/rust.yml
Resovles https://github.com/rapiz1/rathole/issues/17
=> Adopt cargo hack to test each feature

Cargo.toml, src/client.rs, src/lib.rs, src/server.rs, src/transport/mod.rs
Resolves https://github.com/rapiz1/rathole/issues/28
=> feat: separate `noise` as a crate feature

Cargo.lock, Cargo.toml
**Changelog**
- Support Noise
- Support UDP
=> chore: bump v0.2.0

Cargo.lock, Cargo.toml, README.md, src/cli.rs, src/client.rs, src/config.rs, src/config_watcher.rs, src/lib.rs, src/main.rs, src/server.rs, tests/common/mod.rs, tests/integration_test.rs
Resolves https://github.com/rapiz1/rathole/issues/4
=> Support hot reloading

.github/workflows/rust.yml, tests/for_tcp/noise_transport.toml, tests/for_tcp/tcp_transport.toml, tests/for_tcp/tls_transport.toml, tests/for_udp/noise_transport.toml, tests/for_udp/tcp_transport.toml, tests/for_udp/tls_transport.toml, tests/integration_test.rs
- Build releases and upload artifacts
- Build on windows, ubuntu and macos
- Disable TLS tests on macos
- Some efficiency improvements of CI
=> ci: build release, upload artifacts and other improvements

Cargo.toml, src/lib.rs
Resolves https://github.com/rapiz1/rathole/issues/46
=> fix: panic on top-level errors

README.md, examples/systemd/README.md
1. Useful for a long-running task
Thanks.
=> Add instruction to run as service

.dockerignore, Dockerfile
=> chore: Add Dockerfile

Cargo.lock, Cargo.toml, src/main.rs
Resolves https://github.com/rapiz1/rathole/issues/87
=> feat: emit colored log only when STDOUT is a tty

src/helper.rs
Resolves https://github.com/rapiz1/rathole/issues/92
=> fix: support IPv6 `local_address` for UDP

src/client.rs, src/server.rs
Resolves https://github.com/rapiz1/rathole/issues/97
=> fix: flush when handshaking

src/client.rs, src/config_watcher.rs, src/protocol.rs, src/server.rs, src/transport/mod.rs
- Use compact error logging format
- Set data channel logging level to warn
- Make span name clearer
- Other improvements about logging
=> fix: improve log

Cargo.lock, Cargo.toml, src/client.rs, src/helper.rs, src/server.rs
Follows https://github.com/rapiz1/rathole/pull/121
=> fix: reimplement `retry_notify` with signals

Cargo.toml
Set `codegen-units` to 1 for releases so as to improve the performance.
=> fix: set `codegen-units` to 1

src/config_watcher.rs
use unbounded channels in `config_watcher` to avoid potential thread blocking
=> fix: use unbounded channels in `config_watcher`

.github/workflows/rust.yml
Resolves https://github.com/rapiz1/rathole/issues/137
=> ci: fix missing artifacts

src/client.rs
Fixes https://github.com/rapiz1/rathole/issues/143
=> fix: restart when heartbeat times out

docs/out-of-scope.md
Add description about https://github.com/rapiz1/rathole/issues/183.
=> docs: update out-of-scope

src/client.rs, src/config_watcher.rs, src/lib.rs, src/server.rs
=> refactor: hot reload
