- Cargo.lock
- Cargo.toml
- src/transport/noise.rs
- tests/integration_test.rs
- Update to `snowstorm v0.1.3` to fix a critical bug.
- Fix the integration tests to reflect the real testing results
- Set keepalive for the noise transport
Resolves https://github.com/rapiz1/rathole/issues/24
Resolves https://github.com/rapiz1/rathole/issues/23
> Fix noise transport

- Cargo.toml
- README.md
- docs/build-guide.md
This can reduce a binary with feature `client` **from 3 MiB to 500KiB**, which is impressive!
> feat: opt binary size for `minimal` profile

- .github/workflows/release.yml
- .github/workflows/rust.yml
Resolves: https://github.com/rapiz1/rathole/issues/53
> ci: add multiple platform releases

- build.rs
Hey! Recently I tried to build `rathole` from the source tarball and got this error:
```
Compiling rathole v0.3.1 (/build/rathole/src/rathole-0.3.1)
error: failed to run custom build command for `rathole v0.3.1 (/build/rathole/src/rathole-0.3.1)`
Caused by:
process didn't exit successfully: `/build/rathole/src/rathole-0.3.1/target/release/build/rathole-b8f03abef0c5fe3e/build-script-build` (exit status: 1)
--- stderr
Error: could not find repository from '/build/rathole/src/rathole-0.3.1'; class=Repository (6); code=NotFound (-3)
warning: build failed, waiting for other jobs to finish...
error: build failed
```
This PR fixes this issue by running `vergen` twice if it fails, with disabling the "git" feature. This won't be an issue since `option_env!` is used for these git-related variables. …
> fix: update build script for using vergen without a git repo

- src/config.rs
- src/config_watcher.rs
The PR fixes the bug that when `[client]` and `[server]` are present in one file, hot-reloading only works for the `[server]` block.
Resolves https://github.com/rapiz1/rathole/issues/67
> fix: hot-reload for client and server both present

- src/client.rs
- src/protocol.rs
- src/server.rs
Resolves https://github.com/rapiz1/rathole/issues/75
> fix: cancel safety and more logs

- src/server.rs
when you see a loads of 'control channel incoming', don't panic. it's a typo :)
> fix: a log typo

- Cargo.toml
remove unused file in crate
see also https://github.com/the-lean-crate/criner#the-criner-waste-report
```
┌───────────────────────────────────────────────────────────┬─────────────┐
│ Removed File                                              │ Size (Byte) │
├───────────────────────────────────────────────────────────┼─────────────┤
│ .rustfmt.toml                                             │          31 │
│ .gitignore                                                │          32 │
│ .dockerignore                                             │         101 │
│ examples/minimal/server.toml                              │         109 │
│ examples/minimal/client.toml                              │         114 │
│ examples/udp/server.toml                                  │         122 │
│ …
```
> chore: reduce crate size

- src/server.rs
- src/transport/mod.rs
- src/transport/noise.rs
- src/transport/tcp.rs
- src/transport/tls.rs
- Make `Transport::accept` cancel safe. Resolves https://github.com/rapiz1/rathole/issues/84
- Add a timeout for transport handshake.
> feat: make `accept` cancel safe and add a timeout

- Cargo.lock
- Cargo.toml
- README-zh.md
- README.md
- src/client.rs
- src/config.rs
- src/helper.rs
- src/server.rs
- src/transport/mod.rs
- src/transport/noise.rs
- src/transport/tcp.rs
- src/transport/tls.rs
Resolves https://github.com/rapiz1/rathole/issues/79
> feat: expose TCP_NODELAY and TCP_KEEPALIVE

- src/client.rs
- src/constants.rs
Current backoff is always 1s, which is too long if the channel is broken due to a transient network interrupt. Use exponential backoff to make the reconnecting more frequently.
> fix: use exp backoff for running control channel

- src/config.rs
Deny any unknown fields in the configuration check to make it fool proof
> fix: deny unknown fields for config

- .github/workflows/release.yml
It turns out that `-musl` target for mips32 is dynamically linked and doesn't work for many devices. Use glibc instead.
> fix: link aginst glibc instead of muslc on mips32

- Cargo.lock
- Cargo.toml
- src/client.rs
- src/helper.rs
- src/server.rs
Some retries don't respect the shutdown signal. It's not a problem for ctrl-c because the main thread will always exit. But in some race conditions, some tasks will try listening at an unusable address and thus emit useless logs, which is a waste of the resource.
> fix: respect shutdown signal when retry

- src/config.rs
`token`, `default_token`, `local_private_key` will be logged as `MASKED' even if it's in debug level.
like:
```
DEBUG rathole: Config { server: Some(ServerConfig { bind_addr: "0.0.0.0:2333", default_token: Some(MASKED), services: {"foo1": ServerServiceConfig { service_type: Tcp, name: "foo1", bind_addr: "0.0.0.0:5202", token: Some(MASKED), nodelay: None }}, transport: TransportConfig { transport_type: Noise, nodelay: false, keepalive_secs: 10, keepalive_interval: 3, tls: None, noise: Some(NoiseConfig { pattern: "Noise_NK_25519_ChaChaPoly_BLAKE2s", local_private_key: Some(MASKED), remote_public_key: None }) } }), client: None }
```
Resolves https://github.com/rapiz1/rathole/issues/128
> feat: mask out token in logging

- src/config_watcher.rs
by watching the parent dir of config file, we can receive events regardless of the inode of the config file.
fix #76
> fix(config_watcher): allow backupcopy for vim

- README.md
- src/client.rs
- src/config.rs
- src/lib.rs
- src/protocol.rs
- src/server.rs
- src/transport/mod.rs
When connecting via a proxy, TCP keepalive can't make sure the whole connection is alive. Also in practice, some firewalls are found to intercept keepalive ACK packets. So application layer heartbeat is helpful in these cases.
> feat: application layer heartbeat

- .github/workflows/rust.yml
This pull request disables incremental compilation in CI.
> CI builds often are closer to from-scratch builds, as changes are typically much bigger than from a local edit-compile cycle. For from-scratch builds, incremental adds an extra dependency-tracking overhead. It also significantly increases the amount of IO and the size of ./target, which make caching less effective.
ref: https://matklad.github.io/2021/09/04/fast-rust-builds.html
> Make CI Workflow faster

- .github/workflows/rust.yml
Reverts rapiz1/rathole#140
I added a environment variable to `rust.yml` in #140. However, I found that the rust-cache action does this already.
> Revert "Make CI Workflow faster"

- src/config_watcher.rs
This is a proposed fix for #154 
I have chosen to replicate the logic present in [notify's inotify implementation](https://github.com/notify-rs/notify/blob/baafb165e4213c3ba3c3e0f2cc19df677888957d/src/inotify.rs#L586). In the notify crate, these checks make it so that there is no error when presenting a watcher with an empty path (`""`) on Linux, but they are missing from MacOS's fsevent implementation, and therefore I propose to always offer the watcher an absolute path.
Another possible solution is to handle the error returned from this call:
```rust
watcher.watch(parent_path, RecursiveMode::NonRecursive)?;
```
using something like
```rust
if let Err(e) = watcher.watch(parent_path, RecursiveMode::NonRecursive) {
// handle...
}
```
but this means that one could not run rathole on MacOS …
> Make watcher's path absolute for notify's MacOS fsevent implementation

- src/client.rs
- src/helper.rs
- src/transport/mod.rs
- src/transport/noise.rs
- src/transport/tcp.rs
- src/transport/tls.rs
Cache the rathole server IP address in the client for one session, which is, a control channel starting up and shutting down. This only affects the client. The server will not cache any DNS queries ( and it shouldn't ).
Resolves https://github.com/rapiz1/rathole/issues/151
> feat: cache dns result for one session

- examples/systemd/rathole@.service
- examples/systemd/ratholec.service
- examples/systemd/ratholec@.service
- examples/systemd/ratholes.service
- examples/systemd/ratholes@.service
This patch fixes a warning generated by some new version of systemd. Use
"User=nobody" seems to be considered unsafe. So maybe we need to fix it
in our example files.
```
● ratholec@hitmc.service - Rathole Client Service
Loaded: loaded (/etc/systemd/system/ratholec@.service; enabled; vendor preset: enabled)
Active: active (running) since Sat 2022-09-03 23:38:43 CST; 1h 27min ago
Main PID: 507903 (rathole)
Tasks: 14 (limit: 76731)
Memory: 6.9M
CPU: 39.908s
CGroup: /system.slice/system-ratholec.slice/ratholec@hitmc.service
└─507903 /usr/local/bin/rathole -c /etc/rathole/hitmc.toml
Sep 03 23:38:43 <hostname> systemd[1]: Started Rathole Client Service.
...
Sep 03 23:39:25 <hostname> systemd[1]: /etc/systemd/system/ratholec@.service:7: Special user nobody configured, this is not safe! …
```
> [example][systemd] use `DynamicUser=yes`

- src/config.rs
- src/transport/tls.rs
Fallback to system default when client config contains no `trusted_root` parameter.
> Allow use of system default TLS trusted root

- .github/workflows/release.yml
upx v4.0.0 is finally released and contains many bugfixes. Let's shift to it.
> ci: upgrade upx to v4.0.0

- Cargo.lock
- Cargo.toml
Currently the Arch Linux package of `rathole` isn't [reproducible](https://reproducible-builds.org/): https://reproducible.archlinux.org/api/v0/builds/364854/diffoscope
This is due to the current version of `vergen` used in the project not respecting the [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) variable.
> `SOURCE_DATE_EPOCH` is a standardised environment variable that distributions can set centrally and have build tools consume this in order to produce reproducible output.
Luckily, the latest version of `vergen` supports `SOURCE_DATE_EPOCH` timestamps: https://github.com/rustyhorde/vergen/releases/tag/7.4.2 ([commit](https://github.com/rustyhorde/vergen/commit/fd937e863993021849802c303eedc53437f5fd35))
This PR bumps the `vergen` version thus …
> chore: bump `vergen` crate to support `SOURCE_DATE_EPOCH`

- README-zh.md
- README.md
- src/client.rs
- src/config.rs
- src/constants.rs
- Add `retry_interval` for the client to configure the interval between retries to connect to the server.
- The retry backoff now increases more rapidly and is more randomized to avoid flooding a slow network when outage.
Resovles https://github.com/rapiz1/rathole/issues/197
> feat: configurable client retry interval

- README-zh.md
- README.md
- src/transport/mod.rs
Users have reported use cases like MC servers, rdp https://github.com/rapiz1/rathole/issues/171 https://github.com/rapiz1/rathole/issues/209 for rathole. These interactive applications greatly benefit from the TCP_NODELAY flag, which is by default off. Considering large files transferring and web disk application usage for rathole is relatively rare. And even with TCP_NODELAY, rathole provides good bandwidth utilization. It will be reasonable to enable TCP_NODELAY by default.
Users who host web disk applications can still opt out TCP_NODELAY by configuration.
> fix: enable TCP_NODELAY by default

- README-zh.md
which has been fixed in README.md but zh hasn't
>  chore: fix shield.io badge in README-zh.md

- Cargo.lock
- Cargo.toml
- Dockerfile
- README-zh.md
- README.md
- src/client.rs
- src/config.rs
- src/server.rs
- src/transport/mod.rs
- src/transport/tls.rs
- src/transport/websocket.rs
- tests/for_tcp/websocket_tls_transport.toml
- tests/for_tcp/websocket_transport.toml
- tests/for_udp/websocket_tls_transport.toml
- tests/for_udp/websocket_transport.toml
- tests/integration_test.rs
#134 
~~*n.b.: currently udp test is stuck~~
> feat(transport): add websocket transport

- .github/workflows/release.yml
- Cargo.toml
I added dependencies to Cargo, ensuring that OpenSSL is correctly included with features during the compilation of musl, eliminating the need to separately handle OpenSSL for musl. We still find musl necessary because handling dependencies can be quite challenging.
#300
> Add easy musl

- Cargo.lock
resolves #328
This is the output of
```
cargo update curve25519-dalek@4.1.2
```
> chore: Update dependencies in Cargo.lock

- src/helper.rs
- src/server.rs
Without flushing this may sit in a kernel buffer and we won't know if the channel is still alive. This is particularly problematic for the TCP connection pool.
I added flushing to the UDP handling as well, but it's less critical there.
I added a `write_and_flush` to helper, and then use that where needed.
> Flush DataChannelCmd::StartForward* commands

- .github/workflows/release.yml
In this PR, when the target is `aarch64-apple-darwin`, the tests for Native build are bypassed because it seems to fail. However, it can compile successfully and the compiled binary has been tested to run properly on Apple Silicon Mac.
```
➜  ~ file rathole
rathole: Mach-O 64-bit executable arm64
```
I tested the [Actions release](https://github.com/missuo/rathole/actions/runs/6383356395).
> ci: support apple aarch64

- Cargo.lock
- Cargo.toml
This patch fixes two problems:
1. Cargo refuses to compile with `musl` target and without `native-tls` feature. Since #301, `openssl` was incorrectly declared as a required dependency for `musl`, even if the the `native-tls` feature is disabled.
2. The time crate refuses to compile on 1.80.0-nightly toolchain.  Bumped it to include the relevant patch https://github.com/time-rs/time/pull/671
> fix musl non-TLS build

- src/client.rs
- src/config.rs
- src/helper.rs
- tests/config_test/valid_config/full.toml
This implements #184 
I tested it manually behind my ISP's Dual Stack lite with an external Server supporting both ipv4 and ipv6. Both A and AAAA registries were added for the tested domain.
> Implement prefer IPv6 option for the client
